### ISSUE TITLE
install to complicated

### ISSUE THREAD

**Issue by lzomedia** [GoLavaCMS/GoLavaCMS#2]
i'm trying to install this and use it in my project but i'm having issues with the install process

**Comment by abedputra** [comment]
are you familiar with laravel?

**Comment by lzomedia** [comment]
I am familiar with Laravel but I don't get the fact that I need to replace one of the core files of the framework , that will affect futures updates right ?

**Comment by abedputra** [comment]
It just, only added features, if you don't want to replace that file, you just edit the home controller.

**Comment by lzomedia** [comment]
Is just me or I think you should provide a better way to install your cms

**Comment by abedputra** [comment]
Hi,

thanks for the advice, i will fix it.

Thanks
