### ISSUE TITLE
To many If and else 

### ISSUE THREAD

**Issue by lzomedia** [GoLavaCMS/GoLavaCMS#3]
Don't you think you have too many if and else in that code, have you tried to get more knowledge in how laravel does requests ? have you ever heard about factories, repositories? try reading about them. 
https://github.com/GoLavaCMS/GoLavaCMS/blob/master/app/Http/Controllers/FrontendController.php

**Comment by abedputra** [comment]
Thank you for suggest.
Many programer use if else for fulfill the purpose of making the program. So, please respect the programer who make the program.
Please dont use this, if you won't.
And please report bug, error, or add feature, not others.
Thank you..
